version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "alexadbload"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-n7pah350h8v3"
s3_prefix = "alexadbload"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
